build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage/clover.xml'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {}

filter:
    excluded_paths:
        - 'tests/*'
